
DROP DATABASE IF EXISTS PROYECTO;

CREATE DATABASE PROYECTO DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE PROYECTO;

-- Grupo 1

CREATE TABLE USUARIOS (
	dni VARCHAR( 9 ) PRIMARY KEY,
	nom_usuario VARCHAR( 30 ) NOT NULL,
	apellidos VARCHAR( 30 ) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE TIENDAS (
	idtienda SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nom_tienda VARCHAR( 30 ) NOT NULL,
	direccion VARCHAR( 30 ) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE MEMORIASRAM (
	idmemoriaRAM TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	capacidadRAM SMALLINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE MEMORIASROM (
	idmemoriaROM TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	capacidadROM SMALLINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE MARCAS_MODELOS (
	idmarca TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nom_marca VARCHAR( 17 ) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE MARCAS_HARDWARE (
	idmarca2 TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	tipo VARCHAR( 30 ) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE COMPONENTES (
	idcomponente SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nom_componente VARCHAR( 30 ) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Grupo 2

CREATE TABLE TIENDAS_CONTIENEN_COMPONENTES (
	idtienda SMALLINT UNSIGNED,
	idcomponente SMALLINT UNSIGNED,
	PRIMARY KEY ( idtienda, idcomponente ),
	CONSTRAINT fktiendacomponente FOREIGN KEY ( idtienda ) REFERENCES TIENDAS ( idtienda ),
	CONSTRAINT fkcomponentecomponente FOREIGN KEY ( idcomponente ) REFERENCES COMPONENTES ( idcomponente )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE MODELOS (
	idmodelo SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nom_modelo VARCHAR( 17 ) NOT NULL,
	idmarca TINYINT UNSIGNED NOT NULL,
	CONSTRAINT fkmodelomarca FOREIGN KEY ( idmarca ) REFERENCES MARCAS_MODELOS ( idmarca )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Grupo 3

CREATE TABLE MOVILES (
	idmovil SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nom_movil VARCHAR( 30 ) NOT NULL,
	precio FLOAT( 6, 2 ) UNSIGNED NOT NULL,
	pantalla VARCHAR( 5 ) NOT NULL,
	sistema_ope VARCHAR( 20 ) NOT NULL,
	camara TINYINT UNSIGNED NOT NULL,
	bateria SMALLINT UNSIGNED NOT NULL,
	color VARCHAR( 20 ) NOT NULL,
	imagen VARCHAR( 50 ) NOT NULL,
	idmodelo SMALLINT UNSIGNED,
	CONSTRAINT fkmovilmodelo FOREIGN KEY ( idmodelo ) REFERENCES MODELOS ( idmodelo )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Grupo 4

CREATE TABLE TIENDAS_VENDER_MOVILES (
	idtienda SMALLINT UNSIGNED,
	idmovil SMALLINT UNSIGNED,
	PRIMARY KEY ( idtienda, idmovil ),
	CONSTRAINT fkmoviltienda FOREIGN KEY ( idtienda ) REFERENCES TIENDAS ( idtienda ),
	CONSTRAINT fktiendamovil FOREIGN KEY ( idmovil ) REFERENCES MOVILES ( idmovil )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE MOVILESREL (
	idmovil SMALLINT UNSIGNED,
	idmovil2 SMALLINT UNSIGNED,
	PRIMARY KEY ( idmovil, idmovil2 ),
	CONSTRAINT fkmovilrelmovil FOREIGN KEY ( idmovil ) REFERENCES MOVILES ( idmovil ),
	CONSTRAINT fkmovilrelmovil2 FOREIGN KEY ( idmovil2 ) REFERENCES MOVILES ( idmovil )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE MOVILES_ELEGIR_CAPACIDAD (
	idmovil SMALLINT UNSIGNED,
	idmemoriaRAM TINYINT UNSIGNED,
	idmemoriaROM TINYINT UNSIGNED,
	PRIMARY KEY ( idmovil, idmemoriaRAM, idmemoriaROM ),
	CONSTRAINT fkcapacidadmovil FOREIGN KEY ( idmovil ) REFERENCES MOVILES ( idmovil ),
	CONSTRAINT fkcapacidadRAM FOREIGN KEY ( idmemoriaRAM ) REFERENCES MEMORIASRAM ( idmemoriaRAM ),
	CONSTRAINT fkcapacidadROM FOREIGN KEY ( idmemoriaROM ) REFERENCES MEMORIASROM ( idmemoriaROM )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE HARDWARE (
	idhardware TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nucleo VARCHAR( 15 ) NOT NULL,
	idmarca2 TINYINT UNSIGNED NOT NULL,
	CONSTRAINT fkhardwaremarca FOREIGN KEY ( idmarca2 ) REFERENCES MARCAS_HARDWARE ( idmarca2 )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Grupo 5

CREATE TABLE COMPRAS (
	idtienda SMALLINT UNSIGNED,
	idmovil SMALLINT UNSIGNED,
	dni VARCHAR( 9 ),
	PRIMARY KEY ( idtienda, idmovil, dni ),	
	fech_compra DATE NOT NULL,
	CONSTRAINT fkcomprartienda FOREIGN KEY ( idtienda, idmovil ) REFERENCES TIENDAS_VENDER_MOVILES ( idtienda, idmovil ),
	CONSTRAINT fkcomprardni FOREIGN KEY ( dni ) REFERENCES USUARIOS ( dni )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE MOVILES_TIENEN_HARDWARE (
	idmovil SMALLINT UNSIGNED,
	idhardware TINYINT UNSIGNED,
	PRIMARY KEY ( idmovil, idhardware ),
	cpu VARCHAR( 2 ) NOT NULL,
	vel_cpu FLOAT( 3, 2 ) UNSIGNED NOT NULL,
	CONSTRAINT fktenermovil FOREIGN KEY ( idmovil ) REFERENCES MOVILES ( idmovil ),
	CONSTRAINT fktenerhardware FOREIGN KEY ( idhardware ) REFERENCES HARDWARE ( idhardware )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

